keys:
  account_settings.delete
  actions.unfollow
  actions.follow
  actions.block
  actions.unblock
  actions.view_more
  radio.create_new_station
  blocks.blocked
  datetime.distance_in_words.less_than_x_minutes
  datetime.distance_in_words.x_days
  datetime.distance_in_words.x_hours
  datetime.distance_in_words.x_minutes
  datetime.distance_in_words.x_seconds
  actions.pending
  actions.show_more
  activity.no_more_activity
  basics.done
  actions.cancel

