defaults: &defaults
  client_id: 0000000044018ADD
  secret: Zgz2AOyvRUVPhcRk4WnixgvDhZPjkzHP

development:
  <<: *defaults

staging:
  <<: *defaults
  client_id: 0000000048046D5E
  secret: CZ3siPiOlJlkblO5ilEe2fdH1EvFtZlp

production:
  <<: *defaults

