
module CustomArtistsHelper

  SCRIPTS = {
    :msncaen => {
      'detour' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_en-ca_Cyloop_Detour',{"id": "IVP_en-ca_Cyloop_Detour","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx?tag=ENCA_Cyloop%3AENCA_Cyloop_Detour&ns=VC_Source&mk=en-ca&sf=ActiveStartDate&vs=0","bsbpg":"MSVBS2","pg":"VSECA3","partnerlogo":"true","mkt":"en-ca","skin":"2","t":"Cyloop","fr":"IVP_en-ca_Cyloop_Detour","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %Q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "en-ca", "gallery.vcMarket": "en-ca", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_en-ca_Cyloop_Detour", "gallery.categoryRequests": "videoByTag.aspx?tag=ENCA_Cyloop%3AENCA_Cyloop_Detour&ns=VC_Source&mk=en-ca&sf=ActiveStartDate&vs=0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        },
      'invasion' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_en-ca_Cyloop_Invasion',{"id": "IVP_en-ca_Cyloop_Invasion","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx?tag=ENCA_Cyloop%3AENCA_Cyloop_Invasion&ns=VC_Source&mk=en-ca&sf=ActiveStartDate&vs=0","bsbpg":"MSVBS2","pg":"VSECA3","partnerlogo":"true","mkt":"en-ca","skin":"2","t":"Cyloop","fr":"IVP_en-ca_Cyloop_Invasion","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "en-ca", "gallery.vcMarket": "en-ca", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_en-ca_Cyloop_Invasion", "gallery.categoryRequests": "videoByTag.aspx?tag=ENCA_Cyloop%3AENCA_Cyloop_Invasion&ns=VC_Source&mk=en-ca&sf=ActiveStartDate&vs=0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        }
                 },
    :msnmx => {
      'detour' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_ es-mx_Cyloop_Detour',{"id": "IVP_ es-mx_Cyloop_Detour","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DESMX_Cyloop%3AESMX_Detour%26ns%3DVC_Source%26mk%3Des-mx%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"MSVP14","pg":"MSVPR6","partnerlogo":"true","mkt":"es-mx","skin":"2","t":"MX Musica","fr":"IVP_ es-mx_Cyloop_Detour","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "es-mx", "gallery.vcMarket": "es-mx", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_ es-mx_Cyloop_Detour", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DESMX_Cyloop%3AESMX_Detour%26ns%3DVC_Source%26mk%3Des-mx%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        },
      'invasion' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_ es-mx_Cyloop_Invasion',{"id": "IVP_ es-mx_Cyloop_Invasion","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DESMX_Cyloop%3AESMX_Invasion%26ns%3DVC_Source%26mk%3Des-mx%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"MSVP14","pg":"MSVPR6","partnerlogo":"true","mkt":"es-mx","skin":"2","t":"MX Musica","fr":"IVP_ es-mx_Cyloop_Invasion","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "es-mx", "gallery.vcMarket": "es-mx", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_ es-mx_Cyloop_Invasion", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DESMX_Cyloop%3AESMX_Invasion%26ns%3DVC_Source%26mk%3Des-mx%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        }
    },
    :cyloop => {
      'detour' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_es-us_Cyloop_Detour',{"id": "IVP_ es-us_Cyloop_Detour","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DESUS_Cyloop%3AESUS_Detour%26ns%3DVC_Source%26mk%3Des-us%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"ESULO2","pg":"ESULO1","partnerlogo":"true","mkt":"es-us","skin":"2","t":"US Musica","fr":"IVP_es-us_Cyloop_Detour","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "es-us", "gallery.vcMarket": "es-us", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_es-us_Cyloop_Detour", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DESUS_Cyloop%3AESUS_Detour%26ns%3DVC_Source%26mk%3Des-us%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        },
      'invasion' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_es-us_Cyloop_Invasion',{"id": "IVP_es-us_Cyloop_Invasion","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DESUS_Cyloop%3AESUS_Invasion%26ns%3DVC_Source%26mk%3Des-us%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"ESULO2","pg":"ESULO1","partnerlogo":"true","mkt":"es-us","skin":"2","t":"US Musica","fr":"IVP_es-us_Cyloop_Invasion","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "es-us", "gallery.vcMarket": "es-us", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_ es-us_Cyloop_Invasion", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DESUS_Cyloop%3AESUS_Invasion%26ns%3DVC_Source%26mk%3Des-us%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        }
    },
    :msnlatam => {
      'detour' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_es-xl_Cyloop_Detour',{"id": "IVP_es-xl_Cyloop_Detour","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DESXL_Cyloop%3AESXL_Cyloop_Detour%26ns%3DVC_Source%26mk%3Des-xl%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"LAVIBS","pg":"LACYL4","partnerlogo":"true","mkt":"es-xl","skin":"2","t":"Musica","fr":"IVP_es-xl_Cyloop_Detour","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "es-xl", "gallery.vcMarket": "es-xl", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_es-xl_Cyloop_Detour", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DESXL_Cyloop%3AESXL_Cyloop_Detour%26ns%3DVC_Source%26mk%3Des-xl%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        },
      'invasion' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_es-xl_Cyloop_Invasion',{"id": "IVP_es-xl_Cyloop_Invasion","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DESXL_Cyloop%3AESXL_Cyloop_Invasion%26ns%3DVC_Source%26mk%3Des-xl%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"LAVIBS","pg":"LACYL4","partnerlogo":"true","mkt":"es-xl","skin":"2","t":"Musica","fr":"IVP_es-xl_Cyloop_Invasion","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "es-xl", "gallery.vcMarket": "es-xl", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_es-xl_Cyloop_Invasion", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DESXL_Cyloop%3AESXL_Cyloop_Invasion%26ns%3DVC_Source%26mk%3Des-xl%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        }
    },
    :msncafr => {
      'detour' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_fr-ca_Cyloop_Detour',{"id": "IVP_fr-ca_Cyloop_Detour","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx?tag=FRCA_Cyloop%3AFRCA_Cyloop_Detour&ns=VC_Source&mk=fr-ca&sf=ActiveStartDate&vs=0","bsbpg":"MSVBS3","pg":"VSFCA3","partnerlogo":"true","mkt":"fr-ca","skin":"2","t":"Cyloop","fr":"IVP_ fr-ca_Cyloop_Detour","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "fr-ca", "gallery.vcMarket": "fr-ca", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_ fr-ca_Cyloop_Detour", "gallery.categoryRequests": "videoByTag.aspx?tag=FRCA_Cyloop%3AFRCA_Cyloop_Detour&ns=VC_Source&mk=fr-ca&sf=ActiveStartDate&vs=0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        },
      'invasion' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_fr-ca_Cyloop_Invasion',{"id": "IVP_fr-ca_Cyloop_Invasion","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx?tag=FRCA_Cyloop%3AFRCA_Cyloop_Invasion&ns=VC_Source&mk=fr-ca&sf=ActiveStartDate&vs=0","bsbpg":"MSVBS3","pg":"VSFCA3","partnerlogo":"true","mkt":"fr-ca","skin":"2","t":"Cyloop","fr":"IVP_ fr-ca_Cyloop_Invasion","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "fr-ca", "gallery.vcMarket": "fr-ca", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_ fr-ca_Cyloop_Invasion", "gallery.categoryRequests": "videoByTag.aspx?tag=FRCA_Cyloop%3AFRCA_Cyloop_Invasion&ns=VC_Source&mk=fr-ca&sf=ActiveStartDate&vs=0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        }
    },
    :msnbr => {
      'detour' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_pt-br_Cyloop_Detour',{"id": "IVP_pt-br_Cyloop_Detour","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DPTBR_Cyloop%3APTBR_Detour%26ns%3DVC_Source%26mk%3Dpt-br%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"MSVBR3","pg":"MSVBR6","partnerlogo":"true","mkt":"pt-br","skin":"2","t":"BR Musica","fr":"IVP_pt-br_Cyloop_Detour","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "pt-br", "gallery.vcMarket": "pt-br", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_pt-br_Cyloop_Detour", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DPTBR_Cyloop%3APTBR_Detour%26ns%3DVC_Source%26mk%3Dpt-br%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        },
      'invasion' =>
        {'video'   => %q!Msn.Video.BuildPlayer('IVP_pt-br_Cyloop_Invasion',{"id": "IVP_pt-br_Cyloop_Invasion","ifs":"true","ps": "99","c": "vcq","vcq":"videoByTag.aspx%3Ftag%3DPTBR_Cyloop%3APTBR_Invasion%26ns%3DVC_Source%26mk%3Dpt-br%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0","bsbpg":"MSVBR3","pg":"MSVBR6","partnerlogo":"true","mkt":"pt-br","skin":"2","t":"BR Musica","fr":"IVP_pt-br_Cyloop_Invasion","fg":"gtlv2","ad":"true","spl":"false","rv":"true","timePlaying":"180","playlistmin":"1","ch": "true","title":"true"},640,418,'http://images.video.msn.com/flash/soapbox1_1.swf');!,
         'gallery' => %q!Msn.Video.BuildGallery('hot_widget',640,250,{ "gallery.tabCustom": "false", "gallery.dispContainer": "false","gallery.mkt": "pt-br", "gallery.vcMarket": "pt-br", "gallery.showPlaylist": "false", "gallery.playType": "inline", "gallery.playerId": "IVP_pt-br_Cyloop_Invasion", "gallery.categoryRequests": "videoByTag.aspx%3Ftag%3DPTBR_Cyloop%3APTBR_Invasion%26ns%3DVC_Source%26mk%3Dpt-br%26sf%3DActiveStartDate%26sd%3D-1%26vs%3D0", "gallery.autoLoadVideo": "none","cssPath": "http://blstc.msn.com/br/intl/ice/css/1/videogalleryWidgetTop.css", "gallery.linkbackLocation": "hidden", "gallery.pageInfoLocation": "top_right", "gallery.pageControlsLocation": "top_right", "gallery.searchBoxLocation": "hidden", "gallery.categoryMenuLocation": "hidden", "gallery.previewVolume": "100", "gallery.listViewImageLocDetail": "hidden", "gallery.listViewImageLocGrid": "hidden", "gallery.listViewImageLocList": "hidden", "gallery.defaultView": "Grid", "gallery.allowedViews": "Detail%3BGrid%3BList%3B", "gallery.useAutoPage": "true", "gallery.autoPageCategories": "false", "gallery.autoPageMax": "99", "gallery.autoPageTimer": "15", "gallery.dispRss": "top_left", "gallery.dispUpload": "hidden","gallery.numRowsDetail": "2", "gallery.numColsDetail": "5","gallery.imageWidthDetail": "80","gallery.imageWidthGrid": "80","gallery.imageWidthList": "80", "gallery.imageHeightDetail": "60", "gallery.imageHeightGrid": "60", "gallery.imageHeightList": "60","gallery.dispSourceGrid": "false", "gallery.dispDescriptionGrid": "false", "gallery.dispDateGrid": "false","gallery.dispTitleDetail": "true", "gallery.dispSourceDetail": "false", "gallery.dispDescriptionDetail": "false", "gallery.dispDateDetail": "false","gallery.numRowsGrid": "2", "gallery.numColsGrid": "5","gallery.dispDateList": "false","gallery.numRowsList": "2", "gallery.numColsList": "5"},"hot","http://images.video.msn.com/flash/gallerywidget/1_0/gallerywidget.swf");!
        }
    }
  }

  SCRIPTS[:msnlatino] = SCRIPTS[:cyloop]
  SCRIPTS[:cyloopes] = SCRIPTS[:cyloop]
  SCRIPTS[:tvn] = SCRIPTS[:cyloop]

  def custom_artist_video( kind )
    SCRIPTS[current_site.code.to_sym][kind.downcase]['video']
  end

  def custom_artist_gallery( kind )
    SCRIPTS[current_site.code.to_sym][kind.downcase]['gallery']
  end

end

